apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    env: prod
    app: ks8-django
spec:
  selector:
    matchLabels:
      project: django
  template:
    metadata:
      labels:
        project: django
    spec:
      containers:
        - name: django
          image: django_app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: DATABASE_URL
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: ALLOWED_HOSTS
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: DEBUG